// Code generated by ent, DO NOT EDIT.

package entInit

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/gothunder/thunder/internal/events/outbox/ent/entInit/outboxmessage"
	"github.com/gothunder/thunder/internal/events/outbox/ent/entInit/predicate"
)

// OutboxMessageQuery is the builder for querying OutboxMessage entities.
type OutboxMessageQuery struct {
	config
	ctx        *QueryContext
	order      []outboxmessage.OrderOption
	inters     []Interceptor
	predicates []predicate.OutboxMessage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OutboxMessageQuery builder.
func (omq *OutboxMessageQuery) Where(ps ...predicate.OutboxMessage) *OutboxMessageQuery {
	omq.predicates = append(omq.predicates, ps...)
	return omq
}

// Limit the number of records to be returned by this query.
func (omq *OutboxMessageQuery) Limit(limit int) *OutboxMessageQuery {
	omq.ctx.Limit = &limit
	return omq
}

// Offset to start from.
func (omq *OutboxMessageQuery) Offset(offset int) *OutboxMessageQuery {
	omq.ctx.Offset = &offset
	return omq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (omq *OutboxMessageQuery) Unique(unique bool) *OutboxMessageQuery {
	omq.ctx.Unique = &unique
	return omq
}

// Order specifies how the records should be ordered.
func (omq *OutboxMessageQuery) Order(o ...outboxmessage.OrderOption) *OutboxMessageQuery {
	omq.order = append(omq.order, o...)
	return omq
}

// First returns the first OutboxMessage entity from the query.
// Returns a *NotFoundError when no OutboxMessage was found.
func (omq *OutboxMessageQuery) First(ctx context.Context) (*OutboxMessage, error) {
	nodes, err := omq.Limit(1).All(setContextOp(ctx, omq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{outboxmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (omq *OutboxMessageQuery) FirstX(ctx context.Context) *OutboxMessage {
	node, err := omq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OutboxMessage ID from the query.
// Returns a *NotFoundError when no OutboxMessage ID was found.
func (omq *OutboxMessageQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = omq.Limit(1).IDs(setContextOp(ctx, omq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{outboxmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (omq *OutboxMessageQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := omq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OutboxMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OutboxMessage entity is found.
// Returns a *NotFoundError when no OutboxMessage entities are found.
func (omq *OutboxMessageQuery) Only(ctx context.Context) (*OutboxMessage, error) {
	nodes, err := omq.Limit(2).All(setContextOp(ctx, omq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{outboxmessage.Label}
	default:
		return nil, &NotSingularError{outboxmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (omq *OutboxMessageQuery) OnlyX(ctx context.Context) *OutboxMessage {
	node, err := omq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OutboxMessage ID in the query.
// Returns a *NotSingularError when more than one OutboxMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (omq *OutboxMessageQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = omq.Limit(2).IDs(setContextOp(ctx, omq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{outboxmessage.Label}
	default:
		err = &NotSingularError{outboxmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (omq *OutboxMessageQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := omq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OutboxMessages.
func (omq *OutboxMessageQuery) All(ctx context.Context) ([]*OutboxMessage, error) {
	ctx = setContextOp(ctx, omq.ctx, "All")
	if err := omq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OutboxMessage, *OutboxMessageQuery]()
	return withInterceptors[[]*OutboxMessage](ctx, omq, qr, omq.inters)
}

// AllX is like All, but panics if an error occurs.
func (omq *OutboxMessageQuery) AllX(ctx context.Context) []*OutboxMessage {
	nodes, err := omq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OutboxMessage IDs.
func (omq *OutboxMessageQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if omq.ctx.Unique == nil && omq.path != nil {
		omq.Unique(true)
	}
	ctx = setContextOp(ctx, omq.ctx, "IDs")
	if err = omq.Select(outboxmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (omq *OutboxMessageQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := omq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (omq *OutboxMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, omq.ctx, "Count")
	if err := omq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, omq, querierCount[*OutboxMessageQuery](), omq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (omq *OutboxMessageQuery) CountX(ctx context.Context) int {
	count, err := omq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (omq *OutboxMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, omq.ctx, "Exist")
	switch _, err := omq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entInit: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (omq *OutboxMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := omq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OutboxMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (omq *OutboxMessageQuery) Clone() *OutboxMessageQuery {
	if omq == nil {
		return nil
	}
	return &OutboxMessageQuery{
		config:     omq.config,
		ctx:        omq.ctx.Clone(),
		order:      append([]outboxmessage.OrderOption{}, omq.order...),
		inters:     append([]Interceptor{}, omq.inters...),
		predicates: append([]predicate.OutboxMessage{}, omq.predicates...),
		// clone intermediate query.
		sql:  omq.sql.Clone(),
		path: omq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Topic string `json:"topic,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OutboxMessage.Query().
//		GroupBy(outboxmessage.FieldTopic).
//		Aggregate(entInit.Count()).
//		Scan(ctx, &v)
func (omq *OutboxMessageQuery) GroupBy(field string, fields ...string) *OutboxMessageGroupBy {
	omq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OutboxMessageGroupBy{build: omq}
	grbuild.flds = &omq.ctx.Fields
	grbuild.label = outboxmessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Topic string `json:"topic,omitempty"`
//	}
//
//	client.OutboxMessage.Query().
//		Select(outboxmessage.FieldTopic).
//		Scan(ctx, &v)
func (omq *OutboxMessageQuery) Select(fields ...string) *OutboxMessageSelect {
	omq.ctx.Fields = append(omq.ctx.Fields, fields...)
	sbuild := &OutboxMessageSelect{OutboxMessageQuery: omq}
	sbuild.label = outboxmessage.Label
	sbuild.flds, sbuild.scan = &omq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OutboxMessageSelect configured with the given aggregations.
func (omq *OutboxMessageQuery) Aggregate(fns ...AggregateFunc) *OutboxMessageSelect {
	return omq.Select().Aggregate(fns...)
}

func (omq *OutboxMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range omq.inters {
		if inter == nil {
			return fmt.Errorf("entInit: uninitialized interceptor (forgotten import entInit/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, omq); err != nil {
				return err
			}
		}
	}
	for _, f := range omq.ctx.Fields {
		if !outboxmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entInit: invalid field %q for query", f)}
		}
	}
	if omq.path != nil {
		prev, err := omq.path(ctx)
		if err != nil {
			return err
		}
		omq.sql = prev
	}
	return nil
}

func (omq *OutboxMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OutboxMessage, error) {
	var (
		nodes = []*OutboxMessage{}
		_spec = omq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OutboxMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OutboxMessage{config: omq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, omq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (omq *OutboxMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := omq.querySpec()
	_spec.Node.Columns = omq.ctx.Fields
	if len(omq.ctx.Fields) > 0 {
		_spec.Unique = omq.ctx.Unique != nil && *omq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, omq.driver, _spec)
}

func (omq *OutboxMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(outboxmessage.Table, outboxmessage.Columns, sqlgraph.NewFieldSpec(outboxmessage.FieldID, field.TypeUUID))
	_spec.From = omq.sql
	if unique := omq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if omq.path != nil {
		_spec.Unique = true
	}
	if fields := omq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outboxmessage.FieldID)
		for i := range fields {
			if fields[i] != outboxmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := omq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := omq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := omq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := omq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (omq *OutboxMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(omq.driver.Dialect())
	t1 := builder.Table(outboxmessage.Table)
	columns := omq.ctx.Fields
	if len(columns) == 0 {
		columns = outboxmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if omq.sql != nil {
		selector = omq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if omq.ctx.Unique != nil && *omq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range omq.predicates {
		p(selector)
	}
	for _, p := range omq.order {
		p(selector)
	}
	if offset := omq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := omq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OutboxMessageGroupBy is the group-by builder for OutboxMessage entities.
type OutboxMessageGroupBy struct {
	selector
	build *OutboxMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (omgb *OutboxMessageGroupBy) Aggregate(fns ...AggregateFunc) *OutboxMessageGroupBy {
	omgb.fns = append(omgb.fns, fns...)
	return omgb
}

// Scan applies the selector query and scans the result into the given value.
func (omgb *OutboxMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, omgb.build.ctx, "GroupBy")
	if err := omgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OutboxMessageQuery, *OutboxMessageGroupBy](ctx, omgb.build, omgb, omgb.build.inters, v)
}

func (omgb *OutboxMessageGroupBy) sqlScan(ctx context.Context, root *OutboxMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(omgb.fns))
	for _, fn := range omgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*omgb.flds)+len(omgb.fns))
		for _, f := range *omgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*omgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := omgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OutboxMessageSelect is the builder for selecting fields of OutboxMessage entities.
type OutboxMessageSelect struct {
	*OutboxMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oms *OutboxMessageSelect) Aggregate(fns ...AggregateFunc) *OutboxMessageSelect {
	oms.fns = append(oms.fns, fns...)
	return oms
}

// Scan applies the selector query and scans the result into the given value.
func (oms *OutboxMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oms.ctx, "Select")
	if err := oms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OutboxMessageQuery, *OutboxMessageSelect](ctx, oms.OutboxMessageQuery, oms, oms.inters, v)
}

func (oms *OutboxMessageSelect) sqlScan(ctx context.Context, root *OutboxMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(oms.fns))
	for _, fn := range oms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*oms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
