// Code generated by ent, DO NOT EDIT.

package entInit

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/gothunder/thunder/tests/entInit/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/gothunder/thunder/tests/entInit/outboxmessage"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// OutboxMessage is the client for interacting with the OutboxMessage builders.
	OutboxMessage *OutboxMessageClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.OutboxMessage = NewOutboxMessageClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("entInit: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("entInit: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		OutboxMessage: NewOutboxMessageClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		OutboxMessage: NewOutboxMessageClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		OutboxMessage.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.OutboxMessage.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.OutboxMessage.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *OutboxMessageMutation:
		return c.OutboxMessage.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("entInit: unknown mutation type %T", m)
	}
}

// OutboxMessageClient is a client for the OutboxMessage schema.
type OutboxMessageClient struct {
	config
}

// NewOutboxMessageClient returns a client for the OutboxMessage from the given config.
func NewOutboxMessageClient(c config) *OutboxMessageClient {
	return &OutboxMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `outboxmessage.Hooks(f(g(h())))`.
func (c *OutboxMessageClient) Use(hooks ...Hook) {
	c.hooks.OutboxMessage = append(c.hooks.OutboxMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `outboxmessage.Intercept(f(g(h())))`.
func (c *OutboxMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.OutboxMessage = append(c.inters.OutboxMessage, interceptors...)
}

// Create returns a builder for creating a OutboxMessage entity.
func (c *OutboxMessageClient) Create() *OutboxMessageCreate {
	mutation := newOutboxMessageMutation(c.config, OpCreate)
	return &OutboxMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OutboxMessage entities.
func (c *OutboxMessageClient) CreateBulk(builders ...*OutboxMessageCreate) *OutboxMessageCreateBulk {
	return &OutboxMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OutboxMessageClient) MapCreateBulk(slice any, setFunc func(*OutboxMessageCreate, int)) *OutboxMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OutboxMessageCreateBulk{err: fmt.Errorf("calling to OutboxMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OutboxMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OutboxMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OutboxMessage.
func (c *OutboxMessageClient) Update() *OutboxMessageUpdate {
	mutation := newOutboxMessageMutation(c.config, OpUpdate)
	return &OutboxMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OutboxMessageClient) UpdateOne(om *OutboxMessage) *OutboxMessageUpdateOne {
	mutation := newOutboxMessageMutation(c.config, OpUpdateOne, withOutboxMessage(om))
	return &OutboxMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OutboxMessageClient) UpdateOneID(id uuid.UUID) *OutboxMessageUpdateOne {
	mutation := newOutboxMessageMutation(c.config, OpUpdateOne, withOutboxMessageID(id))
	return &OutboxMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OutboxMessage.
func (c *OutboxMessageClient) Delete() *OutboxMessageDelete {
	mutation := newOutboxMessageMutation(c.config, OpDelete)
	return &OutboxMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OutboxMessageClient) DeleteOne(om *OutboxMessage) *OutboxMessageDeleteOne {
	return c.DeleteOneID(om.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OutboxMessageClient) DeleteOneID(id uuid.UUID) *OutboxMessageDeleteOne {
	builder := c.Delete().Where(outboxmessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OutboxMessageDeleteOne{builder}
}

// Query returns a query builder for OutboxMessage.
func (c *OutboxMessageClient) Query() *OutboxMessageQuery {
	return &OutboxMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOutboxMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a OutboxMessage entity by its id.
func (c *OutboxMessageClient) Get(ctx context.Context, id uuid.UUID) (*OutboxMessage, error) {
	return c.Query().Where(outboxmessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OutboxMessageClient) GetX(ctx context.Context, id uuid.UUID) *OutboxMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OutboxMessageClient) Hooks() []Hook {
	return c.hooks.OutboxMessage
}

// Interceptors returns the client interceptors.
func (c *OutboxMessageClient) Interceptors() []Interceptor {
	return c.inters.OutboxMessage
}

func (c *OutboxMessageClient) mutate(ctx context.Context, m *OutboxMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OutboxMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OutboxMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OutboxMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OutboxMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entInit: unknown OutboxMessage mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		OutboxMessage []ent.Hook
	}
	inters struct {
		OutboxMessage []ent.Interceptor
	}
)
