// Code generated by ent, DO NOT EDIT.

package entInit

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/gothunder/thunder/tests/entInit/outboxmessage"
	"github.com/gothunder/thunder/tests/entInit/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeOutboxMessage = "OutboxMessage"
)

// OutboxMessageMutation represents an operation that mutates the OutboxMessage nodes in the graph.
type OutboxMessageMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	topic         *string
	payload       *[]byte
	headers       *map[string]string
	created_at    *time.Time
	delivered_at  *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*OutboxMessage, error)
	predicates    []predicate.OutboxMessage
}

var _ ent.Mutation = (*OutboxMessageMutation)(nil)

// outboxmessageOption allows management of the mutation configuration using functional options.
type outboxmessageOption func(*OutboxMessageMutation)

// newOutboxMessageMutation creates new mutation for the OutboxMessage entity.
func newOutboxMessageMutation(c config, op Op, opts ...outboxmessageOption) *OutboxMessageMutation {
	m := &OutboxMessageMutation{
		config:        c,
		op:            op,
		typ:           TypeOutboxMessage,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withOutboxMessageID sets the ID field of the mutation.
func withOutboxMessageID(id uuid.UUID) outboxmessageOption {
	return func(m *OutboxMessageMutation) {
		var (
			err   error
			once  sync.Once
			value *OutboxMessage
		)
		m.oldValue = func(ctx context.Context) (*OutboxMessage, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().OutboxMessage.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withOutboxMessage sets the old OutboxMessage of the mutation.
func withOutboxMessage(node *OutboxMessage) outboxmessageOption {
	return func(m *OutboxMessageMutation) {
		m.oldValue = func(context.Context) (*OutboxMessage, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m OutboxMessageMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m OutboxMessageMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("entInit: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of OutboxMessage entities.
func (m *OutboxMessageMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *OutboxMessageMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *OutboxMessageMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().OutboxMessage.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTopic sets the "topic" field.
func (m *OutboxMessageMutation) SetTopic(s string) {
	m.topic = &s
}

// Topic returns the value of the "topic" field in the mutation.
func (m *OutboxMessageMutation) Topic() (r string, exists bool) {
	v := m.topic
	if v == nil {
		return
	}
	return *v, true
}

// OldTopic returns the old "topic" field's value of the OutboxMessage entity.
// If the OutboxMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxMessageMutation) OldTopic(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTopic is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTopic requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTopic: %w", err)
	}
	return oldValue.Topic, nil
}

// ResetTopic resets all changes to the "topic" field.
func (m *OutboxMessageMutation) ResetTopic() {
	m.topic = nil
}

// SetPayload sets the "payload" field.
func (m *OutboxMessageMutation) SetPayload(b []byte) {
	m.payload = &b
}

// Payload returns the value of the "payload" field in the mutation.
func (m *OutboxMessageMutation) Payload() (r []byte, exists bool) {
	v := m.payload
	if v == nil {
		return
	}
	return *v, true
}

// OldPayload returns the old "payload" field's value of the OutboxMessage entity.
// If the OutboxMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxMessageMutation) OldPayload(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPayload is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPayload requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPayload: %w", err)
	}
	return oldValue.Payload, nil
}

// ResetPayload resets all changes to the "payload" field.
func (m *OutboxMessageMutation) ResetPayload() {
	m.payload = nil
}

// SetHeaders sets the "headers" field.
func (m *OutboxMessageMutation) SetHeaders(value map[string]string) {
	m.headers = &value
}

// Headers returns the value of the "headers" field in the mutation.
func (m *OutboxMessageMutation) Headers() (r map[string]string, exists bool) {
	v := m.headers
	if v == nil {
		return
	}
	return *v, true
}

// OldHeaders returns the old "headers" field's value of the OutboxMessage entity.
// If the OutboxMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxMessageMutation) OldHeaders(ctx context.Context) (v map[string]string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHeaders is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHeaders requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHeaders: %w", err)
	}
	return oldValue.Headers, nil
}

// ClearHeaders clears the value of the "headers" field.
func (m *OutboxMessageMutation) ClearHeaders() {
	m.headers = nil
	m.clearedFields[outboxmessage.FieldHeaders] = struct{}{}
}

// HeadersCleared returns if the "headers" field was cleared in this mutation.
func (m *OutboxMessageMutation) HeadersCleared() bool {
	_, ok := m.clearedFields[outboxmessage.FieldHeaders]
	return ok
}

// ResetHeaders resets all changes to the "headers" field.
func (m *OutboxMessageMutation) ResetHeaders() {
	m.headers = nil
	delete(m.clearedFields, outboxmessage.FieldHeaders)
}

// SetCreatedAt sets the "created_at" field.
func (m *OutboxMessageMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *OutboxMessageMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the OutboxMessage entity.
// If the OutboxMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxMessageMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *OutboxMessageMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetDeliveredAt sets the "delivered_at" field.
func (m *OutboxMessageMutation) SetDeliveredAt(t time.Time) {
	m.delivered_at = &t
}

// DeliveredAt returns the value of the "delivered_at" field in the mutation.
func (m *OutboxMessageMutation) DeliveredAt() (r time.Time, exists bool) {
	v := m.delivered_at
	if v == nil {
		return
	}
	return *v, true
}

// OldDeliveredAt returns the old "delivered_at" field's value of the OutboxMessage entity.
// If the OutboxMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxMessageMutation) OldDeliveredAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeliveredAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeliveredAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeliveredAt: %w", err)
	}
	return oldValue.DeliveredAt, nil
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (m *OutboxMessageMutation) ClearDeliveredAt() {
	m.delivered_at = nil
	m.clearedFields[outboxmessage.FieldDeliveredAt] = struct{}{}
}

// DeliveredAtCleared returns if the "delivered_at" field was cleared in this mutation.
func (m *OutboxMessageMutation) DeliveredAtCleared() bool {
	_, ok := m.clearedFields[outboxmessage.FieldDeliveredAt]
	return ok
}

// ResetDeliveredAt resets all changes to the "delivered_at" field.
func (m *OutboxMessageMutation) ResetDeliveredAt() {
	m.delivered_at = nil
	delete(m.clearedFields, outboxmessage.FieldDeliveredAt)
}

// Where appends a list predicates to the OutboxMessageMutation builder.
func (m *OutboxMessageMutation) Where(ps ...predicate.OutboxMessage) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the OutboxMessageMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *OutboxMessageMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.OutboxMessage, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *OutboxMessageMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *OutboxMessageMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (OutboxMessage).
func (m *OutboxMessageMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *OutboxMessageMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.topic != nil {
		fields = append(fields, outboxmessage.FieldTopic)
	}
	if m.payload != nil {
		fields = append(fields, outboxmessage.FieldPayload)
	}
	if m.headers != nil {
		fields = append(fields, outboxmessage.FieldHeaders)
	}
	if m.created_at != nil {
		fields = append(fields, outboxmessage.FieldCreatedAt)
	}
	if m.delivered_at != nil {
		fields = append(fields, outboxmessage.FieldDeliveredAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *OutboxMessageMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case outboxmessage.FieldTopic:
		return m.Topic()
	case outboxmessage.FieldPayload:
		return m.Payload()
	case outboxmessage.FieldHeaders:
		return m.Headers()
	case outboxmessage.FieldCreatedAt:
		return m.CreatedAt()
	case outboxmessage.FieldDeliveredAt:
		return m.DeliveredAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *OutboxMessageMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case outboxmessage.FieldTopic:
		return m.OldTopic(ctx)
	case outboxmessage.FieldPayload:
		return m.OldPayload(ctx)
	case outboxmessage.FieldHeaders:
		return m.OldHeaders(ctx)
	case outboxmessage.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case outboxmessage.FieldDeliveredAt:
		return m.OldDeliveredAt(ctx)
	}
	return nil, fmt.Errorf("unknown OutboxMessage field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OutboxMessageMutation) SetField(name string, value ent.Value) error {
	switch name {
	case outboxmessage.FieldTopic:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTopic(v)
		return nil
	case outboxmessage.FieldPayload:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPayload(v)
		return nil
	case outboxmessage.FieldHeaders:
		v, ok := value.(map[string]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHeaders(v)
		return nil
	case outboxmessage.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case outboxmessage.FieldDeliveredAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeliveredAt(v)
		return nil
	}
	return fmt.Errorf("unknown OutboxMessage field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *OutboxMessageMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *OutboxMessageMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OutboxMessageMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown OutboxMessage numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *OutboxMessageMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(outboxmessage.FieldHeaders) {
		fields = append(fields, outboxmessage.FieldHeaders)
	}
	if m.FieldCleared(outboxmessage.FieldDeliveredAt) {
		fields = append(fields, outboxmessage.FieldDeliveredAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *OutboxMessageMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *OutboxMessageMutation) ClearField(name string) error {
	switch name {
	case outboxmessage.FieldHeaders:
		m.ClearHeaders()
		return nil
	case outboxmessage.FieldDeliveredAt:
		m.ClearDeliveredAt()
		return nil
	}
	return fmt.Errorf("unknown OutboxMessage nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *OutboxMessageMutation) ResetField(name string) error {
	switch name {
	case outboxmessage.FieldTopic:
		m.ResetTopic()
		return nil
	case outboxmessage.FieldPayload:
		m.ResetPayload()
		return nil
	case outboxmessage.FieldHeaders:
		m.ResetHeaders()
		return nil
	case outboxmessage.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case outboxmessage.FieldDeliveredAt:
		m.ResetDeliveredAt()
		return nil
	}
	return fmt.Errorf("unknown OutboxMessage field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *OutboxMessageMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *OutboxMessageMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *OutboxMessageMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *OutboxMessageMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *OutboxMessageMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *OutboxMessageMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *OutboxMessageMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown OutboxMessage unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *OutboxMessageMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown OutboxMessage edge %s", name)
}
