// Code generated by ent, DO NOT EDIT.

package entInit

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gothunder/thunder/tests/entInit/outboxmessage"
	"github.com/gothunder/thunder/tests/entInit/predicate"
)

// OutboxMessageDelete is the builder for deleting a OutboxMessage entity.
type OutboxMessageDelete struct {
	config
	hooks    []Hook
	mutation *OutboxMessageMutation
}

// Where appends a list predicates to the OutboxMessageDelete builder.
func (omd *OutboxMessageDelete) Where(ps ...predicate.OutboxMessage) *OutboxMessageDelete {
	omd.mutation.Where(ps...)
	return omd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (omd *OutboxMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, omd.sqlExec, omd.mutation, omd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (omd *OutboxMessageDelete) ExecX(ctx context.Context) int {
	n, err := omd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (omd *OutboxMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(outboxmessage.Table, sqlgraph.NewFieldSpec(outboxmessage.FieldID, field.TypeUUID))
	if ps := omd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, omd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	omd.mutation.done = true
	return affected, err
}

// OutboxMessageDeleteOne is the builder for deleting a single OutboxMessage entity.
type OutboxMessageDeleteOne struct {
	omd *OutboxMessageDelete
}

// Where appends a list predicates to the OutboxMessageDelete builder.
func (omdo *OutboxMessageDeleteOne) Where(ps ...predicate.OutboxMessage) *OutboxMessageDeleteOne {
	omdo.omd.mutation.Where(ps...)
	return omdo
}

// Exec executes the deletion query.
func (omdo *OutboxMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := omdo.omd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{outboxmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (omdo *OutboxMessageDeleteOne) ExecX(ctx context.Context) {
	if err := omdo.Exec(ctx); err != nil {
		panic(err)
	}
}
