// Code generated by ent, DO NOT EDIT.

package entInit

import (
	"time"

	"github.com/google/uuid"
	"github.com/gothunder/thunder/tests/entInit/outboxmessage"
	"github.com/gothunder/thunder/tests/entInit/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	outboxmessageMixin := schema.OutboxMessage{}.Mixin()
	outboxmessageMixinFields0 := outboxmessageMixin[0].Fields()
	_ = outboxmessageMixinFields0
	outboxmessageFields := schema.OutboxMessage{}.Fields()
	_ = outboxmessageFields
	// outboxmessageDescTopic is the schema descriptor for topic field.
	outboxmessageDescTopic := outboxmessageMixinFields0[1].Descriptor()
	// outboxmessage.TopicValidator is a validator for the "topic" field. It is called by the builders before save.
	outboxmessage.TopicValidator = outboxmessageDescTopic.Validators[0].(func(string) error)
	// outboxmessageDescPayload is the schema descriptor for payload field.
	outboxmessageDescPayload := outboxmessageMixinFields0[2].Descriptor()
	// outboxmessage.PayloadValidator is a validator for the "payload" field. It is called by the builders before save.
	outboxmessage.PayloadValidator = outboxmessageDescPayload.Validators[0].(func([]byte) error)
	// outboxmessageDescCreatedAt is the schema descriptor for created_at field.
	outboxmessageDescCreatedAt := outboxmessageMixinFields0[4].Descriptor()
	// outboxmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	outboxmessage.DefaultCreatedAt = outboxmessageDescCreatedAt.Default.(func() time.Time)
	// outboxmessageDescID is the schema descriptor for id field.
	outboxmessageDescID := outboxmessageMixinFields0[0].Descriptor()
	// outboxmessage.DefaultID holds the default value on creation for the id field.
	outboxmessage.DefaultID = outboxmessageDescID.Default.(func() uuid.UUID)
}
