// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OutboxMessage is the predicate function for outboxmessage builders.
type OutboxMessage func(*sql.Selector)
