// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OutboxMessagesColumns holds the columns for the "outbox_messages" table.
	OutboxMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "topic", Type: field.TypeString},
		{Name: "payload", Type: field.TypeBytes},
		{Name: "headers", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "delivered_at", Type: field.TypeTime, Nullable: true},
	}
	// OutboxMessagesTable holds the schema information for the "outbox_messages" table.
	OutboxMessagesTable = &schema.Table{
		Name:       "outbox_messages",
		Columns:    OutboxMessagesColumns,
		PrimaryKey: []*schema.Column{OutboxMessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "outboxmessage_created_at_delivered_at_topic",
				Unique:  false,
				Columns: []*schema.Column{OutboxMessagesColumns[4], OutboxMessagesColumns[5], OutboxMessagesColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OutboxMessagesTable,
	}
)

func init() {
}
